site_name: Data Structures and Algorithms
site_description: Implementation of various data structures and algorithms
site_url: https://onyonkaclifford.github.io/data-structures-and-algorithms
repo_url: https://github.com/onyonkaclifford/data-structures-and-algorithms
edit_uri: blob/main/docs/
repo_name: onyonkaclifford/data-structures-and-algorithms

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: restructured-text
          setup_commands:
            - import sys
            - sys.path.append("sorting_algorithms")
            - sys.path.append("stacks")
            - sys.path.append("deques")
            - sys.path.append("queues")
            - sys.path.append("linked_lists")
            - sys.path.append("positional_linked_lists")
            - sys.path.append("priority_queues")

            - import os
            - from shutil import copyfile
            - copyfile("README.md", os.path.join("docs", "index.md"))

nav:
  - Home: index.md
  - Algorithms:
      - Sorting Algorithms:
          - Bubble Sort: sorting_algorithms/bubble_sort.md
          - Selection Sort: sorting_algorithms/selection_sort.md
          - Insertion Sort: sorting_algorithms/insertion_sort.md
          - Quick Sort: sorting_algorithms/quick_sort.md
          - Merge Sort: sorting_algorithms/merge_sort.md
  - Data Structures:
      - Stacks:
          - Stack ADT: stacks/stack.md
          - List Stack: stacks/list_stack.md
      - Queues:
          - Queue ADT: queues/queue.md
          - List Queue: queues/list_queue.md
      - Deques:
          - Deque ADT: deques/deque.md
          - List Deque: deques/list_deque.md
      - Linked Lists:
          - Linked List ADT: linked_lists/linked_list.md
          - Singly Linked List: linked_lists/singly_linked_list.md
          - Circularly Singly Linked List: linked_lists/circularly_singly_linked_list.md
          - Doubly Linked List: linked_lists/doubly_linked_list.md
          - Circularly Doubly Linked List: linked_lists/circularly_doubly_linked_list.md
      - Positional Linked Lists:
          - Positional Linked List ADT: positional_linked_lists/positional_linked_list.md
          - Positional Singly Linked List: positional_linked_lists/positional_singly_linked_list.md
          - Positional Doubly Linked List: positional_linked_lists/positional_doubly_linked_list.md
      - Priority Queues:
          - Priority Queue ADT: priority_queues/priority_queue.md
          - Sorted List Priority Queue: priority_queues/sorted_list_priority_queue.md
          - Unsorted List Priority Queue: priority_queues/unsorted_list_priority_queue.md
